name: CI Workflow

on:
  push:
    branches:
      - "feature/*"
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      GUEST_NAME: ${{ secrets.GUEST_NAME }}
      GUEST_EMAIL: ${{ secrets.GUEST_EMAIL }}
      GUEST_PASSWORD: ${{ secrets.GUEST_PASSWORD }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest
