name: Build and Push Docker Image

on:
  push:
    branches:
      - master
      - develop
      - "feature/*"
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: "building docker image"
        run: |
          echo "Building Docker image..."
          ls -al
