import pytest
from app.services.service_base import service_response
from http import HTTPStatus


def test_service_response_success(app):
    """
    Tests the service response function for a successful operation and
    ensures it returns the proper status code and response structure.

    Args:
        app: A test application or context required to run the service
            response.

    Raises:
        AssertionError: If the response structure, message, category,
            or status code do not match the expected values.
    """
    data = {"key": "value"}
    response, status_code = service_response(
        status_code=HTTPStatus.OK,
        message="Operation successful",
        category="success",
        data=data
    )

    assert status_code == HTTPStatus.OK
    assert response["data"] == data
    assert response["message"] == "Operation successful"
    assert response["category"] == "success"


def test_service_response_error(app):
    """
    Tests the response generated by the service_response function when the response
    indicates an error. This test ensures that the function returns the expected
    HTTP status code along with the properly formatted response dictionary
    containing a message, category, and data.

     Args:
        app: A test application or context required to run the service
            response.
    """
    response, status_code = service_response(
        status_code=HTTPStatus.NOT_FOUND,
        message="Not found",
        category="error",
        data=None
    )

    assert status_code == HTTPStatus.NOT_FOUND
    assert response["data"] is None
    assert response["message"] == "Not found"
    assert response["category"] == "error"


def test_service_response_danger(app):
    """
    Tests the service_response function for handling error responses with a
    specific category of "danger". This function verifies that the generated
    response and its HTTP status code match the expected values when a server
    error scenario is simulated.

    Parameters
    ----------
    app : Flask
        The Flask application instance to be used during the test. Its presence
        ensures that the test is performed within an application context.

    Raises
    ------
    AssertionError
        If the response or status code does not match the expected values.
    """
    response, status_code = service_response(
        status_code=HTTPStatus.INTERNAL_SERVER_ERROR,
        message="Server error",
        category="danger",
        data=None
    )

    assert status_code == HTTPStatus.INTERNAL_SERVER_ERROR
    assert response["data"] is None
    assert response["message"] == "Server error"
    assert response["category"] == "danger"


def test_service_response_invalid_status_code(app):
    """
    Tests the service_response function with an invalid status code.

    This function verifies that the service_response function raises a
    ValueError when provided with an invalid HTTP status code. It ensures
    proper validation of the status_code input.

    Args:
        app: Fixture representing the application context, typically
            used for testing purposes.

    Raises:
        ValueError: If the provided status_code is invalid, indicating
            an unsupported HTTP status code.

    """
    with pytest.raises(ValueError, match="Invalid HTTP status code"):
        service_response(
            status_code=99,
            message="Invalid input",
            category="error",
            data=None
        )


def test_service_response_invalid_category(app):
    """
    Tests the service_response function for handling invalid category input.

    This test ensures that the function raises a ValueError with the appropriate
    message when an invalid category is provided.

    Args:
        app: The test application or fixture required to invoke the service_response
        function in the context of the test environment.

    Raises:
        ValueError: If the category provided to service_response is not among the
        allowed values ("success", "error", "warning", "danger").
    """
    with pytest.raises(ValueError, match="Category must be one of: danger, error, success, warning"):
        service_response(
            status_code=HTTPStatus.OK,
            message="Invalid category",
            category="invalid",
            data=None
        )
